name: 'Foundry Manifest Update Action'
description: 'GitHub Action to Update Foundry VTT Manifest in main After a Release'
inputs:
  actionToken:
    description: 'Github Token'
    required: true
    default: 'World'
  manifestFileName:
    description: 'Name of the Foundry Manifest File, either system.json or module.json'
    required: true
    default: 'module.json'
  manifestProtectedTrue:
    description: 'Set to true to keep protected:true in the manifest once it is checked back in, otherwise it will be set back to false'
    required: false
    default: "false"
runs:
  using: 'node12'
  main: 'index.js'